### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by htor** [htor/sc-editor#2]
# todo

- [x] output _all_ output from sclang (boot, errors, exit)
- [x] output object/array return values from sclang
- [x] hide docs, hide output keyboard shortcuts
- [x] make panels resizable by dragging
- [x] auto-indent in editor
- [x] lookup name under cursor
- [x] make app logo
- [x] package app somehow
- [x] cmd+l mark lines
- [x] shift+cmd+d duplicate lines
- [x] log errors to file
- [x] new file, open file, saving, window title
- [x] fix menu items
- [x] text zoom per pane
